---
title: "5 2nd BC"
author: "Yuqi Zhang"
date: "2025-05-27"
output: html_document
---


```{r setup, include=FALSE}
karma_dir <- "/Users/yuqzha/LIBRO1_BCSTO/Karma_Libro1"

sthlm_dir <- "/Users/yuqzha/LIBRO1_BCSTO/Stockholm women"
setwd(sthlm_dir)
swecan <- read_sas("Data/reg_swecan_221231.sas7bdat", NULL)

setwd(karma_dir)
karma_swecan <- read_sas("./Data_raw/Karma/reg_swedish_cancer_prework.sas7bdat", NULL) |> 
 # select(!exportid) |> 
  rename(id = studieid, diadat = diadatn)

libro1_swecan <- read_sas("./Data_raw/Libro1/reg_swedish_cancer_prework.sas7bdat", NULL) |> 
  rename(id = starts_with("studie"), diadat = diadatn)
```
## cohort 1
```{r}
bc <- swecan |> 
  # filter(ben != 3) |>  ## exclude benign diseases
  filter(str_sub(icd7, 1, 3) == "170") |> 
  filter(!is.na(diadat)) |> 
  mutate(diadat = diadatn) |> 
  filter(studieid %in% cohort1$id) ## filter id of libro1+karma patients: cohort2
```

get BC diagnosis after first invasive BC date
```{r}
bc_2nd <- cohort1[,c("id", "scr_1st_InviCancer_date")] |> 
  inner_join(bc, join_by(id == studieid), suffix = c("_1st", "_2nd")) |> 
  filter(diadat >= scr_1st_InviCancer_date %m+% months(6)) |> ## 6 months gap
  #filter(ben != "3") |> 
  group_by(id, diadat, sida) |>  ## some duplicates for cancer on same side and same date, might be coding error (1 have >20 records)
  slice(1) 

dup <- bc_2nd |> 
  ungroup() |> 
  mutate(dup = duplicated(id)) |> 
  group_by(id) |> 
  filter(max(dup) ==1) ## 90 records of 45, 10 are cancers on both sides and some are cancers later

bc_2nd <- bc_2nd |> 
  group_by(id) |> 
  arrange(diadat) |>  # choose the 2nd BC
  slice(1) 
```

```{r}
cohort1 <- cohort1 |> 
  left_join(bc_2nd[, c("id", "diadat")], join_by(id == id), suffix = c("_1st", "_2nd"))

cohort1 <- cohort1 |> 
  mutate(
         sec_BC = ifelse(is.na(diadat_2nd), 0,1),
         outcome_date = case_when(
           is.na(diadat_2nd) ~ ymd("2022-12-31"), 
           TRUE ~ diadat_2nd),
         time_var = (as.numeric(outcome_date) - as.numeric(diadat_1st)) / 365.25) 

cohort <- cohort1 |> 
  filter(insitu!=1)
```

```{r}
sec_BC_inc <- cohort |> 
  group_by(detection_mode_1) |> 
  summarise(
    event = sum(sec_BC),
    yp = sum(time_var),
    inc = event/yp
  )
```


```{r cars}
swecan <- bind_rows(karma_swecan,libro1_swecan)

bc <- swecan |> 
  # filter(ben != 3) |>  ## exclude benign diseases
  filter(str_sub(icd7, 1, 3) == "170") |> 
  filter(!is.na(diadat)) |> 
  filter(id %in% cohort2$id) ## filter id of libro1+karma patients: cohort2
```

get BC diagnosis after first BC date (diadat)
```{r}
bc_2nd <- cohort2[,c("id", "diadat")] |> 
  inner_join(bc, join_by(id == id),suffix = c("_1st", "_2nd")) |> 
  filter(diadat_2nd >= diadat_1st %m+% months(6)) |> ## 6 months gap
  #filter(ben != "3") |> 
  group_by(id, diadat_2nd, sida) |>  ## some duplicates for cancer on same side and same date, might be coding error (1 have >20 records)
  slice(1) 

dup <- bc_2nd |> 
  ungroup() |> 
  mutate(dup = duplicated(id)) |> 
  group_by(id) |> 
  filter(max(dup) ==1) ## 90 records of 45, 10 are cancers on both sides and some are cancers later

bc_2nd <- bc_2nd |> 
  group_by(id) |> 
  arrange(diadat_2nd) |>  # choose the 2nd BC
  slice(1) 
```

## quick look cohort 2, PTV and CRC
```{r}
cohort2 <- cohort2 |> 
  left_join(bc_2nd[, c("id", "diadat_2nd")], join_by(id == id)) 

cohort2 <- cohort2 |> 
   mutate(crc = ifelse(is.na(diadat_2nd), 0, 1),
          crc_date = case_when(
            !is.na(diadat_2nd) ~ diadat_2nd,  # Has second cancer
            !is.na(death_date) ~ pmin(death_date, ymd("2022-05-07")),  # No second cancer, has death date
            TRUE ~ ymd("2022-05-07")  # No second cancer, no death date - use end of follow-up
          ),
          protein_LOF_rare_variants_exonic = case_when(
            protein_LOF_rare_variants_exonic == 2 ~ 1,
            TRUE ~ protein_LOF_rare_variants_exonic)
          )
```

```{r}
library(survival)
library(survminer)

cohort <- cohort2

cohort <- cohort2 |> 
  filter(detection_mode == 2)

CRC <- Surv(time = as.numeric(cohort$crc_date) - as.numeric(cohort$diadat), 
            event = cohort$crc)
```

```{r}
summary(coxph(CRC ~ protein_LOF_rare_variants_exonic + age_at_diagnosis, data = cohort))
```

```{r}
summary(coxph(CRC ~ BOADICEA + age_at_diagnosis, data = cohort))
```
```{r}
summary(coxph(CRC ~ pinkcat + age_at_diagnosis, data = cohort))
```

